### ISSUE TITLE
Python codesign error

### ISSUE THREAD

**Issue by kylelundstedt** [GuildEducationInc/aws-jumpcloud#16]
Hi there,

I've been running `aws-jumpcloud` on macOS 10.15 without any problem for a few months.  However, today I ran `aws-jumpcloud list`, and got the following error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-jumpcloud/2.0.0/libexec/lib/python3.7/site-packages/keyring/backends/OS_X.py", line 49, in get_password
    return api.find_generic_password(self.keychain, service, username)
  File "/usr/local/Cellar/aws-jumpcloud/2.0.0/libexec/lib/python3.7/site-packages/keyring/backends/_OS_X_API.py", line 103, in find_generic_password
    Error.raise_for_status(status)
  File "/usr/local/Cellar/aws-jumpcloud/2.0.0/libexec/lib/python3.7/site-packages/keyring/backends/_OS_X_API.py", line 47, in raise_for_status
    "Security Auth Failure: make sure "
keyring.backends._OS_X_API.SecAuthFailure: (-25293, 'Security Auth Failure: make sure python is signed with codesign util')
```

I tried re-installing `aws-jumpcloud` via Homebrew, as well as updating all the related Homebrew packages.  No joy.  Any ideas?

Thanks
Kyle

**Comment by kylelundstedt** [comment]
Tried deleting the `aws-jumpcloud` entry from KeyChain.app.  At that point, running `was-jumpcloud list` says that my profiles are gone.  When I try to add a new profile, I get the same error:

```
~ [1] $ aws-jumpcloud list                                                                                                     (1) (833ms) ┃

No profiles found. Use "aws-jumpcloud add <profile>" to store a new profile.
~ $ aws-jumpcloud add xxxx                                                                                                (753ms)  
Enter the JumpCloud SSO URL for "xxxx": https://sso.jumpcloud.com/...
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-jumpcloud/2.0.0/libexec/lib/python3.7/site-packages/keyring/backends/OS_X.py", line 38, in set_password
    api.set_generic_password(self.keychain, service, username, password)
  File "/usr/local/Cellar/aws-jumpcloud/2.0.0/libexec/lib/python3.7/site-packages/keyring/backends/_OS_X_API.py", line 256, in set_generic_password
    Error.raise_for_status(status)
  File "/usr/local/Cellar/aws-jumpcloud/2.0.0/libexec/lib/python3.7/site-packages/keyring/backends/_OS_X_API.py", line 47, in raise_for_status
    "Security Auth Failure: make sure "
keyring.backends._OS_X_API.SecAuthFailure: (-25293, 'Security Auth Failure: make sure python is signed with codesign util')
```

**Comment by kylelundstedt** [comment]
Had to reset the default KeyChain.app password.  Working now.
